{
    "companies":{
        "cyta":"images/cyta.png",
        "forthnet":"images/forthnet.gif",
        "hol":"images/hol.gif",
        "netone":"images/netone.gif",
        "ontelecoms":"images/ontelecoms.gif",
        "ote":"images/ote.gif",
        "tellas":"images/tellas.gif",
        "vivodi":"images/vivodi.gif",
        "cosmoline":"images/cosmoline.png"
    },
    "configurations":{
        "ΟΤΕ PSTN + ΟΤΕ ADSL 4":{"company":"ote","assets":["ote-pstn","ote-adsl-4"]},
        "ΟΤΕ PSTN Double Play 24 για Φοιτητές":{"company":"ote","assets":["ote-pstn","ote-dp24-foithtes"]},
        "ΟΤΕ PSTN + ΟΤΕ Double Play 2 Απεριόριστα":{"company":"ote","assets":["ote-pstn","ote-dp2-aperiorista"]},
        "ΟΤΕ ISDN + ΟΤΕ Double Play 2 Απεριόριστα":{"company":"ote","assets":["ote-isdn","ote-dp2-aperiorista"]},
        "ΟΤΕ PSTN Double Play 4 Απεριόριστα":{"company":"ote","assets":["ote-pstn","ote-dp4-aperiorista"]},
        "ΟΤΕ PSTN Double Play 4 Απεριόριστα Plus":{"company":"ote","assets":["ote-pstn","ote-dp4-aperiorista-plus"]},
        "ΟΤΕ PSTN Double Play 4 Απεριόριστα - 18 μήνες":{"company":"ote","assets":["ote-pstn","ote-dp4-aperiorista-18months"]},
        "ΟΤΕ PSTN Double Play 4 Απεριόριστα Plus - 18 μήνες":{"company":"ote","assets":["ote-pstn","ote-dp4-aperiorista-plus-18months"]}
    },
    "assets":{
        "ote-pstn":{
            "monthly_charges":12.40,
            "free":{
              "local_and_long_distance":{"secs":0,"min_duration":0,"step":0},
              "mobile":{"secs":0,"min_duration":0,"step":0}
            },
            "categories":{
                "local":{
                    "use_free":"local_and_long_distance",
                    "datetime":[
                        {"days":"MTWTFSS","hours":"012345678901234567890123","tiered_fee":[{"len":-1,"step":60,"charge":0.026}]}
                    ]
                },
                "long_distance":{
                    "use_free":"local_and_long_distance",
                    "datetime":[
                        {"days":"MTWTFS ","hours":"012345678901234567890123","tiered_fee":[{"len":-1,"step":60,"charge":0.055}]},
                        {"days":"      S","hours":"012345678901234567890123","tiered_fee":[{"len":-1,"step":60,"charge":0.026}]}
                    ]
                },
                "mobile":{
                    "use_free":"mobile",
                    "datetime":[
                        {"days":"MTWTFSS","hours":"012345678901234567890123","tiered_fee":[{"len":-1,"step":60,"charge":0.045}]}
                    ]
                }
            }
        },
        "ote-isdn":{
            "copy_of":"ote-pstn",
            "changes":{
                "monthly_charges":"+3.5"
            }
        },
        "ote-dp2-aperiorista-6months":{
            "addon_to":["ote-pstn","ote-isdn"],
            "changes":{
                "monthly_charges":"+9.47",
                "free":{
                    "local_and_long_distance":{"mins":99999999,"min_duration":0,"step":60}
                },
                "categories":{
                    "mobile":{
                        "datetime":[
                            {"days":"MTWTFSS","hours":"012345678901234567890123","tiered_fee":[{"len":-1,"step":60,"charge":0.08}]}
                        ]
                    }
                }
            }
        },
        "ote-dp4-aperiorista":{
            "copy_of":"ote-dp4-aperiorista-18months",
            "changes":{
                "monthly_charges":"+1.626"
            }
        },
        "ote-dp4-aperiorista-plus":{
            "copy_of":"ote-dp4-aperiorista-plus-18months",
            "changes":{
                "monthly_charges":"+1.626"
            }
        },
        "ote-dp4-aperiorista-18months":{
            "addon_to":["ote-pstn","ote-isdn"],
            "changes":{
                "monthly_charges":"+12.722",
                "free":{
                    "local_and_long_distance":{"mins":99999999,"min_duration":0,"step":60},
                    "mobile":{"mins":30,"min_duration":0,"step":60}
                },
                "categories":{
                    "mobile":{
                        "datetime":[
                            {"days":"MTWTFSS","hours":"012345678901234567890123","tiered_fee":[{"len":-1,"step":60,"charge":0.08}]}
                        ]
                    }
                }
            }
        },
        "ote-dp4-aperiorista-plus-18months":{
            "copy_of":"ote-dp4-aperiorista-18months",
            "changes":{
                "monthly_charges":"+3.252",
                "free":{
                    "mobile":{"mins":150,"min_duration":0,"step":60}
                }
            }
        },
        "ote-dp2-aperiorista":{
            "copy_of":"ote-dp2-aperiorista-6months",
            "changes":{
                "monthly_charges":"+4.065"
            }
        },
        "ote-adsl-4":{
            "addon_to":["ote-pstn","ote-isdn"],
            "changes":{
                "monthly_charges":"+14.276"
            }
        },
        "ote-dp24-foithtes":{
            "addon_to":["ote-pstn","ote-isdn"],
            "changes":{
                "monthly_charges":"+6.5"
            }
        }
    }
}
